### ISSUE TITLE
Add completions support to this plugin

### ISSUE THREAD

**Issue by EmilySeville7cfg** [nushell/vscode-nushell-lang#69]
Automatically obtain all available completions and use them while editing scripts: suggesting command options for instance. It would be a neat feature. 😄

**Comment by fdncred** [comment]
We originally had vscode suggestions for subcommands but the thing that makes it difficult in nushell is that subcommands are delimited by space. So, every space you type would trigger the subcommand list. This because annoying so we removed it. I think the code may still be there but commented out. I'm sure there's a better way to do it.

Generating parameters and such may be different though.

We'd accept a PR for any piece of this, assuming it works better than the original implementation. :)

**Comment by EmilySeville7cfg** [comment]
What about generating completions by some shortcut for instance `Ctrl+Space`?

> We'd accept a PR for any piece of this, assuming it works better than the original implementation. :)

I am not sure I personally can do it. I have no

**Comment by fdncred** [comment]
> What about generating completions by some shortcut for instance Ctrl+Space? 

We could do something like that but a big problem is that we don't have a LSP right now. So, I think that means that we'd have to put all these things in typescript i.e. all options, command parameters, etc. Or, we'd have to shell out and call nushell for each of these and parse the return - probably would be non-performant.

**Comment by fdncred** [comment]
Added. Tracking issue is here https://github.com/nushell/vscode-nushell-lang/issues/91

**Comment by EmilySeville7cfg** [comment]
Many thanks! ❤️ 🚀
